Enable MISRA checking in cppcheck
ament/ament_lint pull request #320
Opened 2021-09-02 16:45 UTC by mjeronimo

For Space ROS, the --misra option to cppcheck is enabled by default from ament_cppcheck, since MISRA checking will be required, and a command-line option introduced to disable it.

2021-09-07 21:19 UTC, audrow approved these changes
Looks good to me with green CI. It'd probably be good to run CI on all downstream packages.

2021-09-08 23:50 UTC, nuclearsandwich requested changes
During my first review pass looking at the overall PR diff. Something about this struck me as a little off. The MISRA option is passed from cmake to ament_cppcheck to cppcheck itself but goes through a weird inversion of expression. In the CMake function MISRA is a "positive" argument. ON means MISRA, OFF means not MISRA. But in ament_cppcheck it's a "negative" argument `--disable-misra` present means not MISRA and absent means MISRA. In cppcheck, the option `--addon=misra` argument is again positive.

I took a look at the commit history and saw 5dd935f110f6de2113e03f8cc6ae2245085138d2 which has all "positive" arguments throughout and I think that's actually the best interface for the MISRA argument.

In order to get MISRA checking on by default for spaceros I would suggest updating the ament_cmake_cppcheck hook script to set `MISRA ON` there. https://github.com/ament/ament_lint/blob/master/ament_cmake_cppcheck/cmake/ament_cmake_cppcheck_lint_hook.cmake#L83-L85

2021-09-08 23:55 UTC, mjeronimo commented
Yes, I agree. I'll update accordingly.

2021-09-09 19:46 UTC, nuclearsandwich approved these changes
Looks good to me once the DCO bot is happy. Thanks for iterating!

2021-09-09 21:11 UTC, merged