Add flake8 linter ignore support
ament/ament_lint pull request #424
Opened 2022-11-16 19:56 UTC by RFRIEDM-Trimble

2022-11-16 23:38 UTC, mjeronimo approved these changes

2022-11-17 00:09 UTC, RFRIEDM-Trimble commented
My bad. Missed this when I commented out some code right before push. Will fix. 
`2: cmake/ament_cmake_flake8_lint_hook.cmake:18: Line ends in whitespace [whitespace/eol]`

2022-11-17 00:11 UTC, RFRIEDM-Trimble commented
Fixed the white space, tests should pass.

2022-11-17 07:57 UTC, aprotyas requested changes
Small modification requested by otherwise LGTM

2022-11-17 07:57 UTC, aprotyas commented on ament_cmake_flake8/cmake/ament_flake8.cmake
> +  endif()
You still want to add `ARG_UNPARSED_ARGUMENTS` to your command once you're done processing all arguments.


```suggestion
  if(ARG_EXCLUDE)
    list(APPEND cmd "--exclude" "${ARG_EXCLUDE}")
  endif()
  
  list(APPEND cmd ${ARG_UNPARSED_ARGUMENTS})
```

2022-11-17 07:57 UTC, aprotyas commented
Can someone run CI?

2022-11-17 18:59 UTC, aprotyas approved these changes
@RFRIEDM-Trimble approving preemptively, mind fixing the EOL whitespace issue and amending the commit message to satisfy DCO?

2022-11-17 19:54 UTC, RFRIEDM-Trimble commented
> @RFRIEDM-Trimble approving preemptively, mind fixing the EOL whitespace issue and amending the commit message to satisfy DCO?

Done, the whitespace was already fixed btw.  I didn't realize accepting change suggestions in the UI that it doesn't sign it for me. Sorry for troubles.

2022-12-08 22:54 UTC, mjeronimo commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17789)](http://ci.ros2.org/job/ci_linux/17789/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12335)](http://ci.ros2.org/job/ci_linux-aarch64/12335/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18439)](http://ci.ros2.org/job/ci_windows/18439/)

2022-12-09 05:52 UTC, merged