Added undescore to ignore new pydocstyle item
ament/ament_lint pull request #428
Opened 2023-01-03 15:58 UTC by Crola1702

Signed-off-by: Crola1702 <cristobal.arroyo@ekumenlabs.com>

[Pydocstyle 6.2.0](https://github.com/PyCQA/pydocstyle/releases/tag/6.2.0) introduced a [new feature](https://github.com/PyCQA/pydocstyle/commit/d4d9d6342ff201b5bb4b672ae35ac3e43968190a#diff-e4d54968958770bba400abd39d13bea987e30f73a2cb87fd94d6fb8d9f366162R298) where `get_files_to_check` method yields 4 items instead of 3.

This PR adds and ignores that item, so the tests can run without crashing.

2023-01-03 16:07 UTC, Crola1702 commented
[Rolling CI](https://build.ros2.org/job/Rpr__ament_lint__ubuntu_jammy_amd64/68/consoleFull) is installing Pydocstyle 6.1.1:

```
00:01:00.043 pydocstyle: 6.1.1-1
```

2023-01-03 16:08 UTC, Crola1702 commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17880)](http://ci.ros2.org/job/ci_linux/17880/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12448)](http://ci.ros2.org/job/ci_linux-aarch64/12448/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18554)](http://ci.ros2.org/job/ci_windows/18554/)

Linux CI is upgrading to 6.2.1
```
Collecting pydocstyle
  Downloading pydocstyle-6.2.1-py3-none-any.whl (37 kB)
Collecting pyflakes
  Downloading pyflakes-3.0.1-py2.py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 11.4 MB/s eta 0:00:00
...
pydocstyle==6.2.1
```

2023-01-03 16:19 UTC, clalancette requested changes

2023-01-03 16:19 UTC, clalancette commented on ament_pep257/ament_pep257/main.py
> +    for filename, checked_codes, ignore_decorators, _ in files_to_check:
So this isn't going to work with older pydocstyle, which we still need to support for users who haven't upgraded the pydocstyle yet.

Instead, I think we'll need to first try to unpack 3 values, and if that fails with a `ValueError`, then try to unpack with 4 values.  Alternatively, we could look up the version number of pydocstyle that is currently in use, and choose which one to do based on that (though I think that is a little more brittle).

2023-01-03 16:45 UTC, clalancette requested changes

2023-01-03 16:45 UTC, clalancette commented on ament_pep257/ament_pep257/main.py
> +            }
This definitely works, but duplicates the body of the loop.

I actually just learned about a new Python 3 syntax that lets you unpack an optional set of arguments at the end, `*_`.  So I think we can handle returning 3 or 4 tuple items, without duplicating the body of the loop, with:

```suggestion
    # Unpack 3 values for pydocstyle <= 6.1.1, and 4 values for pydocstyle >= 6.2.0.
    for filename, checked_codes, ignore_decorators, *_ in files_to_check:
        if _filename_in_excludes(filename, excludes):
            continue
        files_dict[filename] = {
            'select': checked_codes,
            'ignore_decorators': ignore_decorators,
        }
```

Can you give this a try and see if it still solves the problem?

2023-01-03 17:22 UTC, clalancette approved these changes
Looks good with green CI!

Please make sure to run CI up to some package that uses `ament_pep257`, as well as on RHEL (to make sure it still works there).

2023-01-03 17:51 UTC, Crola1702 commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17881)](http://ci.ros2.org/job/ci_linux/17881/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12449)](http://ci.ros2.org/job/ci_linux-aarch64/12449/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=18555)](http://ci.ros2.org/job/ci_windows/18555/)
* Rhel [![Build Status](https://ci.ros2.org/job/ci_linux-rhel/281/badge/icon)](https://ci.ros2.org/job/ci_linux-rhel/281/)

2023-01-03 21:57 UTC, clalancette commented
This is all green, so merging this in.

2023-01-03 21:57 UTC, merged

2023-01-12 14:29 UTC, Crola1702 commented
@mergify backport foxy

2023-03-03 05:08 UTC, ijnek commented
Could we please get a release in foxy with this change merged please? I believe everyone's foxy CIs for ros2 python packages are failing without this change released. Thanks!

2023-03-03 18:37 UTC, Crola1702 commented
> Could we please get a release in foxy so we can get this change please?

FYI: @jacobperron

2023-03-06 12:57 UTC, clalancette commented
I'll comment over on the backport PR.