remove AMENT_IGNORE check in clang-tidy when looking for compilation db
ament/ament_lint pull request #441
Opened 2023-06-13 07:46 UTC by alsora

The clang-tidy linter is currently broken in ROS 2 Rolling due to this PR https://github.com/ament/ament_cmake/pull/410

That PR adds an `AMENT_IGNORE` file in all packages build folders.
These folders is where the compilation database is also generated.
Clang-tidy needs the compilation database in order to run, but it currently skips directories with an `AMENT_IGNORE` file in them.

This PR removes this check which seems redundant.

2023-06-22 17:21 UTC, clalancette requested changes
After looking at this, we think the change is OK but we could definitely use a comment here explaining the situation (as laid out in https://github.com/ament/ament_cmake/pull/410#issuecomment-1588296267).

2023-08-25 09:57 UTC, alsora commented
Added comment; sorry for the long wait, but this PR completely fell of my radar.

2023-08-28 18:06 UTC, clalancette requested changes

2023-08-28 18:06 UTC, clalancette commented on ament_clang_tidy/ament_clang_tidy/main.py
> +                # The check would also be redundant, because if a source folder was marked with AMENT_IGNORE, then
Actually, flake8 thinks these lines are too long (they need to be < 100).  Once that is fixed we can run full CI on it.

2023-11-05 15:09 UTC, clalancette approved these changes

2023-11-05 15:10 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19730)](http://ci.ros2.org/job/ci_linux/19730/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14236)](http://ci.ros2.org/job/ci_linux-aarch64/14236/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20456)](http://ci.ros2.org/job/ci_windows/20456/)

2023-11-05 21:07 UTC, merged